
// error-list.js
// These are the initial lists. You can update them here or via the UI and export/import later.

window.ERROR_LISTS = {
  words: [
    // Simple words to flag (default whole-word unless you disable it)
    "BETMGM",
    "BORGATA",
    "alternation",
    "particpate",
    "BRAND",
    "1st",
    "2nd",
    "3rd",
    "4th",
    "5th",
    "6th",
    "7th",
    "8th",
    "9th",
    "10th",
  ],
  phrases: [
    // Multi-word phrases or substrings
    "59 EST", // There should be an AM/PM before
    "59 EST",
    "0 EST",
    "0 ET",
    "eligible game For every",
    "COVID-19 ",
    " e Sponsor",
    "instructions of e ",
    "bonus bonus",
    "Term of Service",
    "BRAND website",
    "0k",
    "5k",
    'Bet winnings (the “(“',    
    'Bet winnings (the "("',    
    'Bet winnings the “(“',
    'Bet winnings the "("',
    'Bet winnings the &ldquo;(&ldquo;',
    'Bet winnings (the &ldquo;(&ldquo;',
    'daysafter',
    'Casino."',
    'Casino.”',
  ],
  specials: [
    // Special characters or sequences (they'll be matched as literal strings)
    "&nbsp;",
    "&nbsp",
    "nbsp",
    "<em>",   // if you want to flag HTML entity usage
    "<br>",
    "<p></p>",
    "<p> </p>",
    "<strong></strong>",
    "<strong> </strong>",
    " ",
    "​​ ",
    " ",
    ": <",
    "s(s)",
    "s[s]",
    " </strong>",
    "[poker or sports]",
    "[sports or poker]",
    "5/$",
    "0/$",
    "0/",
    "5/",
    "0/$",
    "5/1",
    "5/5",
    "0/1",
    "0/5",
    ">:</",
    "$$",
    "..",
    "<ul></ul>",
    "<ul> </ul>",
    "<li></li>",
    "<li> </li>",
    " .",
    " ,",
    "$ ",
  ]
};